version: '3.1'
services:
  keri:
    image: keri/dht:latest
    restart: always
    ports:
      - 23713:23713
      - 23700:23700
    environment:
      NODE_PORT: 23713
      API_HOST: 0.0.0.0
      API_PORT: 23700
      DHT_BOOTSTRAP: localhost:23713
      KERIDHT_THROTTLE: 0.01